services:
  - type: web
    name: universal-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1
